### ISSUE TITLE
Stackoverflow while compiling

### ISSUE THREAD

**Issue by alexarchambault** [lihaoyi/scala-parser#8]
I keep getting StackOverflowErrors while trying to compile scala-parser. Getting them with both Java 7 (OS X) and 8 (Ubuntu 12.04, 14.04), as far as commit a0c39cdb0639a64c3277c8c0b269dd4372892331 (didn't tried further in the past), on a clean config (Ivy cache cleared).

`sbt compile` output like
```
Loading /usr/share/sbt/bin/sbt-launch-lib.bash
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Set current project to scala-parser (in build file:/home/test/tmp/scala-parser/)
[info] Compiling 8 Scala sources to /home/test/tmp/scala-parser/target/scala-2.11/classes...
java.lang.StackOverflowError
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at scala.tools.nsc.typechecker.Namers$Namer.typeErrorHandler(Namers.scala:111)
        at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1539)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:778)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:777)
        at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1565)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:777)
        at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:769)
        at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1681)
        at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1689)
        at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1679)

```

...

```
        at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1628)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4911)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5295)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5322)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5269)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5273)
        at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5351)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2977)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3081)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3081)
        at scala.collection.immutable.List.loop$1(List.scala:172)
        at scala.collection.immutable.List.mapConserve(List.scala:188)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3081)
        at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2340)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5217)
        at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5217)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5216)
        at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5252)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5259)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5295)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5322)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5269)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5273)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5362)
        at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5453)
        at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:876)
[error] (compile:compile) java.lang.StackOverflowError
[error] Total time: 4 s, completed 6 mars 2015 10:16:29
```

Would you have any idea of what could cause that? Am I the only one getting these errors?

**Comment by lihaoyi** [comment]
Yeah, just give your SBT more stack space. It's not infinite recursion,
just a lot =P
